// AutoGenerated: 7/27/2022 6:46:36 AM
public static class MNArrays  
{
// Base Class to move to another project only needs b2 b4 b8 to avoid compile errors. And empty method get array
public static byte[] b2  = new byte[2];
public static byte[] b4  = new byte[4];
public static byte[] b8  = new byte[8];
public static byte[] b9  = new byte[9];
public static byte[] b30  = new byte[30];
public static byte[] b29  = new byte[29];
public static byte[] GetArray(int value)
{
switch (value)
{
  case 2:
  return b2;
  case 4:
  return b4;
  case 8:
  return b8;
  case 9:
  return b9;
  case 30:
  return b30;
  case 29:
  return b29;
default: return new byte[0];}
}
}