using System.Collections;
using System.Collections.Generic;
using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
#endif

/// <summary>
/// Instead of using menu in editor can add to a gameobject. Required if you want to change class name
/// </summary>
public class MNSerializerMono : MonoBehaviour
{

    public string SerializedScriptName = "MNSerializedData.cs";
    public string PathToCode = "/Scripts/AutogeneratedScripts";
    public int MaxString;

    public void CreateSerializedClass()
    {
        string path = Application.dataPath + PathToCode;

        MNCore.CreateSerializedClass(path, SerializedScriptName, MaxString);
    }

}

[CustomEditor(typeof(MNSerializerMono))]
public class MNSerializerMonoEditor : Editor
{

    public override void OnInspectorGUI()
    {
        DrawDefaultInspector();
        MNSerializerMono mono = (MNSerializerMono)target;

        if (GUILayout.Button("Create Serialized Class"))
        {
            mono.CreateSerializedClass();
        }
    }

}




